### ISSUE TITLE
Hamburger navigation menu

### ISSUE THREAD

**Issue by 5jt** [snooseboulevard/snooseboulevard.github.io#9]
Expected

![Screenshot 2021-09-06 at 08 47 30](https://user-images.githubusercontent.com/5923162/132179897-988ebfe4-072f-45ea-bede-7ef88fdf63ca.png)

**Comment by AsfandToor** [comment]
You can assign it to me I have already done it.

**Comment by 5jt** [comment]
Can you push it to the repo as branch `issue9`? (Unsure how the permissions work here.)

**Comment by AsfandToor** [comment]
It's also my first time contributing. Do I just push into your repo? or I have to fork first and then generate a pull request?

**Comment by 5jt** [comment]
Thank you! Do we call you Asfand? 

Closing this issue now and will open a new issue for using the button to toggle the navigation menu. 

Are you participating simply to get the experience?

Stephen

**Comment by AsfandToor** [comment]
Happy to help :). Yes you can call me Asfand. Yes, I am participating to gain experience. I am new to GitHub and this one was my first contribution.
